pkg/providers/vault/vault.go
There are two versions of [Vault KV engine](https://www.vaultproject.io/docs/secrets/kv/index.html).
Vault KV engine version 2 (which is enabled by default on vault cluster creation under `secret/` path) has a bit different response format:
v1: https://www.vaultproject.io/api/secret/kv/kv-v1.html#sample-response
VS
v2: https://www.vaultproject.io/api/secret/kv/kv-v2.html#sample-response-1
Example:
```bash
$ vault secrets enable -path=kvv1 kv
Success! Enabled the kv secrets engine at: kvv1/
$ vault write kvv1/aaa/mysecret abc=xxx
Success! Data written to: kvv1/aaa/mysecret
$ vault write kvv1/data qwerty=123
Success! Data written to: kvv1/data
$ vault secrets enable -path=kvv2 -version=2 kv
Success! Enabled the kv secrets engine at: kvv2/
$ vault kv put kvv2/foo/bar abc=xyz bcd=123
Key …
```
=> Add support for Vault KV engine version 2

pkg/providers/vault/vault.go
After successful `vault login` command token is stored into so-called token-helper file located at `~/.vault-token` [link](https://github.com/hashicorp/vault/blob/50f3870baedb9ef1c8ccdda1792b385aa52939fe/website/source/docs/commands/index.html.md#token-helper).
This PR adds ability to use this file for authenticating requests to vault.
Order of precedence: 1) if VAULT_TOKEN is set, use it, 2) Otherwise: try to use `~/.vault-token` file (if it doesn't exist etc errors won't be generated) 
So, workflow may be simplified a bit to:
```bash
vault login -method=....
vals eval -f myfile.yaml
```
=> vault provider: add ability to retrieve token from ~/.vault-token file

pkg/stringmapprovider/stringmapprovider.go, pkg/stringprovider/stringprovider.go
otherwise we'll get:
```
$ make
go build -o bin/vals ./cmd/vals
go: finding github.com/variantdev/vals/pkg/providers/awssecrets latest
go: finding github.com/variantdev/vals/pkg latest
go: finding github.com/variantdev/vals/pkg/providers latest
build github.com/variantdev/vals/cmd/vals: cannot load github.com/variantdev/vals/pkg/providers/awssecrets: no matching versions for query "latest"
make: *** [build] Error 1
```
=> fix: Remove old awssec package from imports

pkg/providers/vault/vault.go
Fixes #29 
The home directory is already prepended to the file path [here](https://github.com/variantdev/vals/blob/master/pkg/providers/vault/vault.go#L183-L193)
=> fix: prepend homedir only once when reading vault token

README.md
readme calls aws secrets 'awssec', but the actual provider name is 'awssecrets' O_o
see here -> https://github.com/variantdev/vals/blob/master/vals.go#L53 
btw, this also makes the line saying 'The package names corresponds to the URI schemes' incorrect, but I'm not sure how to rephrase it. 
EDIT: Added an  AWS Secrets cross account secret example, while I'm at it...
=> change scheme name in the readme

go.sum, pkg/providers/vault/kv_helper.go, pkg/providers/vault/vault.go
This makes the vals reference opaque to the underlying vault secrets
engine version
=> vault provider: adapt to both v1 and v2 secret paths

README.md, go.mod, go.sum, pkg/providers/azurekeyvault/azurekeyvault.go
Follow up to https://github.com/variantdev/vals/pull/39
This enhances the Azure Key Vault provider to also allow authentication through `az login`.
=> Azure keyvault provider: support credentials from 'az login'

pkg/providers/vault/vault.go
- Support `VAULT_LOGIN_MOUNT_POINT` to specify mount point when the auth method is approle
- The default behaviour is not changed(the default value is set to `/approle`)
=> Add mount point option to vault provider

README.md, vals.go
Hi. I tried to use tfstate schema and noticed I need to use 4 slashes to use the absolute path:
```
ref+tfstate:////home/piotr.roszatycki/Terraform/test/.terraform/terraform.tfstate/foo
```
It is really ugly and odd. Usually tripple slashes is used for absolute paths (like `file:///home/foo`) and no slashes for relative paths. I get that it would be difficult to not use slashes at all then we could follow the pattern that double slash is for relative path like:
```
ref+tfstate://.terraform/terraform.tfstate/foo
```
and tripple for absolute:
```
ref+tfstate:///home/piotr.roszatycki/Terraform/test/.terraform/terraform.tfstate/foo
```
=> Use double slash for relative and tripple slash for absolute path

README.md, pkg/providers/tfstate/tfstate.go, pkg/stringprovider/stringprovider.go, vals.go
This patch adds new schemes that can allow to use direct path to Terraform state in the bucket: one for GCS another for S3.
The patch requires first #47 to be applied as far as it support GCS buckets implemented by tfstate-lookup v0.2.0
It should solve #45
=> New schemas tfstates3 and tfstategs

Makefile, cmd/vals/main.go
Add `vals version` command.
Fixes: #62 
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
=> add version cmd

pkg/providers/sops/sops.go
Should fix #84 
I'm not a Go programmer, so it's possible I've mucked this up, but, it's a pretty simple fix and it does seem to work.
=> fix(sops): decode base64 data before passing to SOPS

README.md, pkg/providers/vault/vault.go
Vault namespaces is an enterprise-only feature that we will start making use of very soon. It is already supported via the `VAULT_NAMESPACE` environment variable, but this adds native support to vals for it so that it can be set in the ref.
This is my first time in go, so please be kind :)
=> Add Vault namespace native support

README.md, pkg/providers/awskms/awskms.go, pkg/stringmapprovider/stringmapprovider.go, pkg/stringprovider/stringprovider.go, vals.go
An alternative implementation of the `awskms` provider, inspired by #41.
This implementation works the way you suggested it should in #41, with `ref+awskms://BASE64CIPHERTEXT` resolving to the cleartext encoded by said ciphertext. The indirection/`ref+vals://` support from #41 is not included.
Note that while I have tested this code and it does work, I am not a Go programmer, so I can't really vouch for its quality. In particular, I didn't understand the intended purpose of having the `GetStringMap` function in addition to the `GetString` function; even with an empty implementation, the `awskms` provider does seem to work, but, I assume it's missing some functionality given that I didn't really properly implement one of the necessary methods.
=> feat: add awskms provider

README.md, pkg/providers/awskms/awskms.go, pkg/providers/sops/sops.go
This switches SOPS to using URL-safe base64 encoding, same as the AWSKMS provider uses.
=> fix(sops): Use URL-safe Base64 encoding

cmd/vals/main.go
I think the back-quoting was not intended.
Compare the original output:
```
Usage of env:
-export export
Prepend exports to each line
-f string
YAML/JSON file to be loaded to set envvars
```
... to the suggested output with this patch:
```
Usage of env:
-export
Prepend 'export' to each line
-f string
YAML/JSON file to be loaded to set envvars
```
=> Fix unwanted back-quoting in usage string

Makefile, cmd/vals/main.go
Fix #96 
Use the ldflags from [goreleaser](https://goreleaser.com/customization/build/).
```
ldflags:
```
=> Fix vals version

README.md
This PR may safe hours of debugging for someone like me
The example from readme dos not work. The error message should contain `vault1.example.com:8200` not ` 127.0.0.1:8200`
```
$ echo "a: ref+vault://mykv/foo#/bar?address=https://vault1.example.com:8200" | vals eval -f -
expand vault://mykv/foo#/bar?address=https://vault1.example.com:8200: Get "https://127.0.0.1:8200/v1/sys/internal/ui/mounts/mykv/foo": dial tcp 127.0.0.1:8200: connect: connection refused
```
New example works as expected the error message has `https://vault1.example.com:8200`.
````
$ echo "a: ref+vault://mykv/foo?address=https://vault1.example.com:8200#/bar" | vals eval -f -
expand vault://mykv/foo?address=https://vault1.example.com:8200#/bar: Get "https://vault1.example.com:8200/v1/sys/internal/ui/mounts/mykv/foo": …
```
=> Fix Vault readme

pkg/providers/gcpsecrets/gcpsecrets.go, pkg/providers/gcpsecrets/gcpsecrets_test.go, vals_gcpsecrets_test.go
Alternate approach for the problem described in https://github.com/variantdev/vals/pull/98
----
We're using this with Helm and dynamic secret keys (e.g. `app__{{ .Environment.Name }}__DB_PASSWORD`, and in some environments we want a fixed value, or we want the value to empty. The fixed value could be solved by adding a secret with that fixed value, but an empty value is not allowed in GCP.
By making a value optional we can safely ignore errors.
=> Add "optional" option to gcpsecrets provider

pkg/providers/gcpsecrets/gcpsecrets.go, pkg/providers/gcpsecrets/gcpsecrets_test.go, vals_gcpsecrets_test.go
We're using this with Helm and dynamic secret keys (e.g. `app__{{ .Environment.Name }}__DB_PASSWORD`, and in some environments we want a fixed value, or we want the value to empty. The fixed value could be solved by adding a secret with that fixed value, but an empty value is not allowed in GCP.
By providing a fallback option an empty string can be set as fallback.
Alternatively an option to ignore missing keys and defaulting to an empty string could work too.
=> Add fallback option to gcpsecrets provider

cmd/vals/main.go, io.go, io_test.go
Fixes #81
Fixes #92
With this change `vals eval` now supports multiple yaml documents. Previosly only the first document would be processed, now it works as expected:
```
$ echo "
> foo: ref+echo://foo
> ---
> bar: ref+echo://bar
> " | vals eval -f -
foo: foo
---
bar: bar
```
This PR also fixes the json output for both `ksdecode` and `eval` commands, since they now share the same input and output code.
=> Add support for multiple yaml documents on eval

README.md, pkg/expansion/expand_match.go, pkg/expansion/expand_match_test.go
Fix the expression syntax to treat new line as the expression terminator to directly fix the issue reported in #57.
I've also updated the documentation with the brand-new "expression syntax" that covers the new treatment of the new-line, so that it's more clear what is supposed to work or not.
Resolves #57
=> Fix expression syntax code and docs

pkg/api/internal.go
I needed to prepend a tab instead of a space before the code block. Otherwise go-fmt flattened some nested YAML lists as go-fmt treated those as godoc "lists" described in https://go.dev/doc/comment
=> Fix some code comment to not break after Go 1.19

cmd/vals/main.go, go.mod, io.go, stream_yaml.go, vals.go, vals_test.go
We already have a command `vals exec` which is usually run like `vals exec -f env.yaml -- other command` so that the other command is run using the fetched secrets as the envvars.
This change makes the `-f` flag optional and adds the new flag `-stream-yaml`.
The new flag instructs vals to read the yaml, run `vals eval` against it, and pipe the result into the stdin of the other command. This is handy when you want more security, by not writing data ccontaining fetched secrets onto the local disk.
For example, `vals exec --stream-yaml objs.yaml -- kubectl apply -f -` is considered a more secure alternative to running `vals eval -f objs.yaml > tmp.yaml && kubectl apply -f tmp.yaml`.
=> feat: vals-exec --stream-yaml $FILE to stream vals-eval result to stdin of another command

cmd/vals/main.go, vals.go
Add two new options to `exec` command:
- `-s`, like other commands, for so called "silent mode"
- `-i`  to have environment inherits variables before being populated/modified
=> Add new options to exec command

README.md, pkg/providers/tfstate/tfstate.go
Hello!
We have a scenario where TFState values are stored across multiple subscriptions. I imagine this will be the case for larger orgs that use DevTest subscriptions or central subscriptions.
This PR will allow users to specify the subscription ID but will still default to the current Azure contexts ID.
So the following will now be possible
```
fooenv: ref+tfstate://storageaccount/environment.tfstate/output.connection_string?az_subscription_id=devtest-subscription-id
foocentral: ref+tfstate://storageaccount/environment.tfstate/output.connection_string?az_subscription_id=central-subscription-id
foodefault: ref+tfstate://storageaccount/environment.tfstate/output.connection_string
```
=> Add Azure Subscription ID support per value

README.md, pkg/awsclicompat/session.go, pkg/providers/awskms/awskms.go, pkg/providers/awssecrets/awssecrets.go, pkg/providers/s3/s3.go, pkg/providers/ssm/ssm.go, vals_awssecrets_test.go
This adds the support for assuming AWS IAM roles via vals ref URLs.
This is an important usability enhancement because we currently support assuming roles only by configuring AWS profiles before calling vals (and helmfile, which is a tool that integrates vals as a library).
In other words, you no longer need to configure AWS profiles to let vals assume role before reading e.g. AWS SSM Parameter Store. Instead, you just give a `role_arn` parameter in the vals ref URL query and vals assumes role for you.
=> Add support for assuming AWS IAM roles without AWS profiles

cmd/vals/main.go, cmd/vals/main_test.go, vals.go
This PR embeds `vals ksdecode` into `vals eval` command.
See #131 as potential use-case.
Additional, the encode kubernetes secrets again. This is important, because `stringData` elements are always merged into `data` map on Kubernetes side. The downside here, that I'm unable to remove key from a secrets.
If there is a string with `{data: {a: "..", b: ".."}}` and I'm running `kubectl apply` with `{data: {a: ".."}}`, then the b property gets removed. However with `{strongData: {a: ".."}}` the b property will be still exists.
Tested with 
```bash
% kubectl create secret generic a --from-literal=a=ref+echo://foo/bar --dry-run=client -o yaml | ./bin/vals eval -kubernetes-secrets
```
=> Add -decode-kubernetes-secrets flag to vals eval

pkg/expansion/expand_match.go, pkg/expansion/expand_match_test.go
The current default ref regex expression matches closing quotes and incorrectly matches spaces when using query params, as seen [here](regexr.com/7i3jf)
The fix corrects the regex expression adds a space and a quote to the greedy match, which should fix the issues, as seen [here](regexr.com/7i3jo)
I added some test cases just to be sure
=> fix: default ref regex should not include spaces and quotes when matching

io.go, io_test.go
Attempt at a fix on the issue I raised in https://github.com/helmfile/vals/issues/165
I'm not sure if this is too heavy of an approach or not, but found that it worked for what I was running into and figured I would propose it.
=> fix empty yaml on documents with comment only sections

Makefile, README.md, pkg/providers/file/file.go, pkg/providers/file/file_test.go
=> Add base64 encoding support to file provider

README.md, go.mod, go.sum, pkg/providers/pulumi/pulumi.go, pkg/providers/pulumi/pulumi_test.go, pkg/stringprovider/stringprovider.go, vals.go
This is an initial implementation of a Pulumi provider backed by state. This first cut meets my use case of obtaining state from the Pulumi REST API. I've updated the readme with the relevant usage and a couple examples.
=> feat(providers) initial implementation of pulumi provider

pkg/awsclicompat/session.go
the AWS SDK and CLI (currently only in Python) allows for configuration of the AWS endpoint URL via the `AWS_ENDPOINT_URL` environment variable [1].
the Golang AWS SDK does not currently support this, but according to GitHub issues, parity is on the way [2].
this change allows for a temporary workaround (it took two years for this support to make it to the Python SDK [3]) that allows `vals` to pick up the `AWS_ENDPOINT_URL` environment variable and configure the session accordingly.
this allows for testing with non-AWS infrastructure like Localstack and Moto, and could even open the door for more comprehensive integration tests of the AWS functionality in this project without the need for using real AWS infrastructure.
[1]: https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoin …
=> support AWS_ENDPOINT_URL configuration

README.md, go.mod, pkg/providers/gkms/gkms.go, pkg/stringmapprovider/stringmapprovider.go, pkg/stringprovider/stringprovider.go, vals.go, vals_gkms_test.go
Add support for GCP KMS. Tested locally.
=> feat(providers): add support for GCP KMS

pkg/providers/k8s/k8s.go, pkg/providers/k8s/k8s_test.go, vals_k8s_test.go
The k8s provider now supports fetching values from ConfigMaps.
Covers: https://github.com/helmfile/vals/issues/187
=> feat(k8s): extend k8s provider to fetch configmap

Makefile, README.md, pkg/providers/k8s/k8s.go, pkg/providers/k8s/k8s_test.go, pkg/stringmapprovider/stringmapprovider.go, pkg/stringprovider/stringprovider.go, vals.go
A simple `vals get ref+k8s://... > result.txt` results in logs (`stderr`) mixing with result (`stdout`).
- fix: remove `fmt.Printf` (-> `p.log.Debugf`) **PRINCIPAL**
- docs: header `Kubernetes secrets` -> `Kubernetes` (because of ConfigMap) 
- refactor: keep `return p, nil` `return k8s.New(l, provider), nil` patterns
- refactor: `return result, err` in some (unparam lint forbids all) custom functions
- feat: add `make lint`
=> fix(providers): k8s, log message getting into stdout

go.mod, pkg/providers/k8s/k8s.go
Attempting to use vals (via helmfile) today, I ran into an error:
...Unable to get Secret ci-runners/runner-cos-cache-keys: Unable to
create the Kubernetes client: no Auth Provider found for name "oidc"
A quick search showed that the solution is to ensure the auth plugins are imported; testing this change locally with a rebuilt helmfile made my auth problems go away.
=> Load all common k8s auth providers

README.md, pkg/providers/pulumi/pulumi.go
The motivation here is to streamline configuration of the Pulumi project and/or stack during value lookups where this information is seldom different per URI and would otherwise mean more duplication.
=> feat(providers): pulumi project/stack set via env var

pkg/expansion/expand_match.go, pkg/expansion/expand_match_test.go
Now allows quotes in the query strings again. 
Added a test for it, but had to remove one tests that expected quotes to be removed.
fixes #230
=> #230 fix: now handles quotes in query string

README.md, go.mod, go.sum, pkg/providers/onepassword/onepassword.go, pkg/stringprovider/stringprovider.go, vals.go, vals_onepassword_test.go
Last July, 1Password announced [Service Accounts](https://blog.1password.com/1password-service-accounts/). We discussed this in #181, but at that moment the Go SDK did not support service accounts.
Earlier this week, 1Password announced [new SDKs](https://blog.1password.com/sdk-beta/).
This PR adds support for retrieving secrets from 1Password using service accounts.
Example: `ref+op://vals-test/vals-test/username`
I have tested this locally and I have added the accompanying test, with setup instructions.
Closes #181
=> feat(providers): Add support for 1Password using service account tokens

README.md, pkg/providers/gcpsecrets/gcpsecrets.go, vals_gcpsecrets_test.go
As seen in https://cloud.google.com/sdk/gcloud/reference/beta/secrets/create, `gcloud secrets create` adds a LF character to the end of the secret value. This is tracked by https://issuetracker.google.com/issues/157867791 for 4 years now. 
This new `trim_nl` parameter removes LFs at the end of the secret value. Default behavior is unchanged.
```shell
$ echo 'secret: "ref+gcpsecrets://project/secret+"' | vals eval -f - -o json 
{"secret":"mysecret\n"}
$ echo 'secret: "ref+gcpsecrets://project/secret?trim_nl=false+"' | vals eval -f - -o json 
{"secret":"mysecret\n"}
$ echo 'secret: "ref+gcpsecrets://project/secret?trim_nl=true+"' | vals eval -f - -o json 
{"secret":"mysecret"}
```
=> feat(gcpsecrets): add trim_nl parameter

.github/workflows/release.yaml
goreleaser action isn't building anymore, see: https://github.com/helmfile/vals/actions/runs/9639191863
=> fix: replaced deprecated rm-dist flag with clean

README.md
Currently the docs explain how to use the `pulumistateapi` provider to access attributes from resources in a Pulumi stack. This is great, but not what most users will want to do, since reaching into particular resources and grabbing their attributes isn't stable compared to using values that have been explicitly exported by calling `pulumi.export`, i.e. the Pulumi stack output. Fortunately the Pulumi API exposes the Pulumi stack output as a resource in the stack, so we can access it using the resource type `pulumi_pulumi_Stack` as now explained in `README.md`.
=> docs: Improve clarity around how to access Pulumi stack outputs

pkg/providers/onepassword/onepassword.go, pkg/providers/onepasswordconnect/onepasswordconnect.go
I noticed that the 1Password providers were very slow, and the amount of time it took to evaluate a YAML file with 1Password references increased approximately linearly with the number of 1Password references, which suggested to me that work was being unnecessarily repeated.
I found that the providers have a `client` field, and its assigned to, but we never check if its set, so we always create a new client. This PR updates the providers so that if the `client` is not set one will be created, and if one has been set then it'll be reused.
For my YAML file with 26 1Password references, this change reduced the time it took to evaluate the file from 29 seconds to 11 seconds. There is still room for improvement (e.g. by parallelizing the evaluation of each ref, improved caching, etc.), but …
=> perf: Reuse 1Password client

vals.go, vals_test.go
We've some use cases where we have plain dictionaries in yaml files and need to evaluate secret refs with vals. We've a workaround/hack to use yq to change this dictionaries into a format that vals likes and then back to it's origin after secrets are evaluated. But this is kinda hacky, thus this PR.
The yq hack (don't mind the extra quotings/escapes as this is part of a larger script):
```sh
yq ". as \$in | {\"data\": \$in} | .data = (eval(.) | .data)" "$file" | vals eval | yq eval ".data" > "${file}.tmp" && mv "${file}.tmp" "$file"
```
=> feat: make vals able to eval dictionaries

README.md, go.mod, pkg/providers/keychain/keychain.go, pkg/providers/keychain/keychain_test.go, vals.go
This pull request adds a new provider for retrieving secrets from the macOS Keychain.
=> feat: Add keychain provider for reading text/yaml/json secrets

README.md
This pull request includes a minor update to the `README.md` file. The change adds a reference link for further information on authentication methods.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R661-R662): Added a link to a GitHub issue for more details on authentication methods.
fix: https://github.com/helmfile/vals/issues/441
=> docs: Add more info link to README for authentication methods

.github/workflows/e2e-test.yaml, .github/workflows/unit-test.yaml
This pull request includes significant changes to the GitHub Actions workflows to better organize and separate concerns between different types of tests. The changes include renaming and restructuring the CI workflow, as well as creating separate workflows for unit tests and end-to-end (E2E) tests.
Changes to GitHub Actions workflows:
* [`.github/workflows/ci.yaml`](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL1-R1): Renamed the workflow from "Go" to "CI" and removed the unit-test job to streamline the CI process. [[1]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL1-R1) [[2]](diffhunk://#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL10) …
=> refactor(ci): Simplify CI workflow by removing unit-test job

io.go, vals_test.go
see: https://github.com/go-yaml/yaml/issues/770
This pull request introduces a new function to handle YAML timestamp parsing and includes a corresponding test to ensure its proper functionality. The most important changes include the addition of the `replaceTimestamp` function and a new test case for evaluating nodes with timestamps.
YAML timestamp handling:
* [`io.go`](diffhunk://#diff-2538bb8c5daf4057de32a936a59f125087b9bb7d0b2832b33e9743456e2a1ea3R73-R98): Added the `replaceTimestamp` function to treat timestamps as strings to avoid incorrect encoding of "YYYY-MM-DD" formats.
Testing:
* [`vals_test.go`](diffhunk://#diff-7ccbe6d5d8a057b65566e71a531774c01d4c1e719a02a133a216e847287b7f5fR152-R185): Added `TestEvalNodesWithTime` to verify that YAML timestamps are correctly treated as …
=> feat: handle timestamps as strings in YAML parsing

io.go, vals_test.go
This pull request includes changes to the `io.go` and `vals_test.go` files to improve the handling of YAML nodes and timestamps. The most important changes include adding the `slices` package, updating the `replaceTimestamp` function, and modifying test cases to include dates in lists.
Improvements to YAML node handling:
* [`io.go`](diffhunk://#diff-2538bb8c5daf4057de32a936a59f125087b9bb7d0b2832b33e9743456e2a1ea3R10): Added the `slices` package to the import list.
* [`io.go`](diffhunk://#diff-2538bb8c5daf4057de32a936a59f125087b9bb7d0b2832b33e9743456e2a1ea3L90-R91): Updated the `replaceTimestamp` function to use `slices.Contains` for checking tags, allowing it to handle both `!!map` and `!!seq` tags.
Enhancements to test cases:
* [`vals_test.go`](diffhunk://#diff-7ccbe6d5d8a057b65566e71a531 …
=> feat: enhance timestamp handling in YAML parsing to support sequences

README.md, pkg/providers/azurekeyvault/azurekeyvault.go
Apologies for the confusion on opening this PR earlier than I intended to.
This PR adds support for being able to choose which authentication method you use for Azure Key Vault, as well as correcting the documentation which incorrectly described how the azidentity Go module currently handled authentication.
Please let me know if you want me to update or change anything!
=> feat: add AZKV_AUTH env var for azure key vault

go.mod, go.sum, pkg/providers/oci/oci.go, pkg/providers/oci/oci_test.go, pkg/stringprovider/stringprovider.go, vals.go
We'd like to have direct OCI support to pull down yaml values.  Issue https://github.com/helmfile/vals/issues/694
This uses the ORAS go library and default docker credentials to access the file.  I'm using the default annotation ORAS looks for and allowing it to be overridden if needed.
=> Add OCI support
