README.md, cmd/vals/main.go, config.go, go.mod, io.go, pkg/providers/awssecrets/awssecrets.go, pkg/providers/sops/sops.go, pkg/providers/ssm/ssm.go, pkg/providers/vault/vault.go, pkg/stringmapprovider/stringmapprovider.go, pkg/stringprovider/stringprovider.go, vals.go, vals_awssecrets_test.go, vals_ssm_test.go, vals_vault_test.go
As the repo was renamed in this PR module & references are renamed
=> fix: Rename module & update references mumoshu/vals -> variantdev/vals

README.md, go.mod, pkg/providers/awssecrets/awssecrets.go, pkg/providers/sops/sops.go, pkg/providers/ssm/ssm.go, pkg/providers/vault/vault.go, vals.go
=> Introduce Runtime object, move caching one level up

README.md
I tried to make the application work with current vault version, with some debugging efforts I could make it work. Main reason is that examples provided are probably outdated, so here is my PR.
=> Update readme according to current Vault version

README.md, go.mod, pkg/providers/vault/vault.go
Add support for approle authentication
Closes #23
=> Add support for app-role authentication when using Vault as Secret Backend

go.mod, pkg/providers/ssm/ssm.go
Enhancement for https://github.com/variantdev/vals/issues/25
=> add ssm parameter versioning

pkg/awsclicompat/session.go, pkg/providers/awssec/awssec.go, pkg/providers/ssm/ssm.go
This PR adds aws profile parameter cfg:
ref+awsssm://dev/dov/token?profile=account
=> feat: add-aws-profile-cfg

pkg/providers/ssm/ssm.go
https://github.com/variantdev/vals/issues/36
=> fix ssm secret revealed to stderr when param version is specified

go.mod, go.sum
Bump aws-sdk-go for using aws sso provider
ref: https://github.com/aws/aws-sdk-go/pull/3755
=> Bump aws-sdk-go

README.md
Relates to https://github.com/fujiwara/tfstate-lookup/pull/23
=> Reflect recent changes of tfstate-lookup regarding output elements

.goreleaser.yml
=> Windows releases support

.goreleaser.yml
Fix version and Git commit for builds via goreleaser.
=> Set version and Git commit on build

README.md
I lost 1 hour with that one :-)
=> docs: remove / before arn of the secret

README.md, pkg/providers/gitlab/gitlab.go, pkg/stringprovider/stringprovider.go, vals.go
It has only been tested with `gitlab.com` unfortunately as I don't have access to on-premises servers at the moment.
=> Adding GitLab support

README.md, pkg/providers/vault/vault.go
Closes https://github.com/variantdev/vals/issues/108
=> Add support of VAULT_TOKEN_FILE env var

README.md
=> Fix wrong flag name in the doc

cmd/vals/main.go, pkg/log/log.go, pkg/providers/awskms/awskms.go, pkg/providers/awssecrets/awssecrets.go, pkg/providers/s3/s3.go, pkg/providers/sops/sops.go, pkg/providers/ssm/ssm.go, pkg/providers/vault/vault.go
=> Enable the silent mode via -s flag

pkg/api/internal.go
Let me remove this unused interface that I found while rereading the whole code base!
=> chore: Removed unused interface

README.md, cmd/vals/main.go, vals.go
=> Add get command and Get function for string input

README.md, pkg/providers/tfstate/tfstate.go
=> Experimental support for specifying aws_profile on tfstate backend

pkg/providers/gcpsecrets/gcpsecrets.go
Resolves https://github.com/helmfile/vals/pull/101#discussion_r1096528265
=> gcpsecrets: fix new provider function

cmd/vals/main.go, pkg/log/log.go, pkg/providers/awssecrets/awssecrets.go, pkg/providers/s3/s3.go, pkg/providers/s3/s3_test.go, pkg/providers/sops/sops.go, pkg/providers/ssm/ssm.go, pkg/providers/ssm/ssm_test.go, pkg/providers/vault/vault.go, pkg/stringmapprovider/stringmapprovider.go, pkg/stringprovider/stringprovider.go, vals.go
Ref https://github.com/helmfile/vals/issues/25#issuecomment-1418271339
=> Make log output configurable per vals runtime

vals.go, vals_test.go
=> fix encode multiple docs

go.mod, go.sum
See fujiwara/tfstate-lookup#139
Ran `go mod tidy`
=> upgrade tfstate-lookup

README.md
Small update to Kubernetes provider documentation in README.
=> chore(doc): update doc for k8s provider

README.md
I found a mistake in the documentation in the section with an example of using Helm.
=> Update README.md for Helm provider

README.md, pkg/providers/bitwarden/bitwarden.go, pkg/providers/bitwarden/bitwarden_test.go, vals.go
This PR adds support for the Bitwarden Vaulmanagement API available in the Bitwarden CLI.
=> feat: Bitwarden provider (helmfile#276)

pkg/expansion/expand_match.go, pkg/expansion/expand_match_test.go
=> fixes regex #393
